Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b553b88b6d8>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 132, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2]
CANCELLED

State before abort: 
  Diversity = 1539
    1-diversity = 0
    2-diversity = 51
    3-diversity = 1488
  #Auts = 1630
  #Isos = 82076
  880469 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../main.py':

     867858.408544      task-clock (msec)         #    0.321 CPUs utilized          
         5,842,630      context-switches          #    0.007 M/sec                  
         1,340,967      cpu-migrations            #    0.002 M/sec                  
       389,883,007      page-faults               #    0.449 M/sec                  
 5,115,186,237,108      cycles                    #    5.894 GHz                    
 5,777,501,306,021      instructions              #    1.13  insn per cycle         
 1,207,711,585,972      branches                  # 1391.600 M/sec                  
    19,125,780,056      branch-misses             #    1.58% of all branches        

    2700.025356465 seconds time elapsed

