Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2ba095e53978>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 132, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 3668
    1-diversity = 4
    2-diversity = 88
    3-diversity = 3576
  #Auts = 3812
  #Isos = 25933
  1026875 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../main.py':

     802784.912901      task-clock (msec)         #    0.297 CPUs utilized          
         6,921,388      context-switches          #    0.009 M/sec                  
         1,513,268      cpu-migrations            #    0.002 M/sec                  
       437,051,779      page-faults               #    0.544 M/sec                  
 5,029,745,516,706      cycles                    #    6.265 GHz                    
 4,756,776,716,234      instructions              #    0.95  insn per cycle         
   987,752,065,106      branches                  # 1230.407 M/sec                  
    19,144,480,901      branch-misses             #    1.94% of all branches        

    2700.062468335 seconds time elapsed

