Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x2af8f99ea240>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 728, in __del__
    self._internal_poll(_deadstate=_maxsize)
  File "/usr/lib/python3.5/subprocess.py", line 1332, in _internal_poll
    self._waitpid_lock.release()
KeyboardInterrupt
Spectrum = [3, 2, 1]
DEFINABLE

Final state: 
  Diversity = 6332
    1-diversity = 4
    2-diversity = 94
    3-diversity = 6234
  #Auts = 6523
  #Isos = 67298
  4212217 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../main.py':

    3575704.536094      task-clock (msec)         #    0.412 CPUs utilized          
        28,946,341      context-switches          #    0.008 M/sec                  
         6,474,694      cpu-migrations            #    0.002 M/sec                  
     1,800,207,105      page-faults               #    0.503 M/sec                  
22,107,099,364,530      cycles                    #    6.183 GHz                    
20,170,210,641,635      instructions              #    0.91  insn per cycle         
 4,179,620,308,494      branches                  # 1168.894 M/sec                  
    77,557,325,025      branch-misses             #    1.86% of all branches        

    8684.614298734 seconds time elapsed

