Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7f4c10b7d748>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 728, in __del__
    self._internal_poll(_deadstate=_maxsize)
KeyboardInterrupt
Spectrum=[3, 2, 1]
Diversity=2327
1-diversity=2
2-diversity=34
3-diversity=2291
#Auts=2381
#Isos=12384
1153541 calls to Minion
DEFINABLE

 Performance counter stats for 'timeout --signal=SIGINT 30m python3 main.py':

     787273.910500      task-clock (msec)         #    0.389 CPUs utilized          
         7,799,856      context-switches          #    0.010 M/sec                  
         1,703,551      cpu-migrations            #    0.002 M/sec                  
       446,929,920      page-faults               #    0.568 M/sec                  
 4,985,922,357,222      cycles                    #    6.333 GHz                    
 4,065,970,259,344      instructions              #    0.82  insn per cycle         
   842,537,610,316      branches                  # 1070.196 M/sec                  
    19,445,075,324      branch-misses             #    2.31% of all branches        

    2024.526971593 seconds time elapsed

